debug: ${DEBUG}
spring:

  redis:
    port: 6379
    host: localhost
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: mygroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: ${POSTGRE_DATABASE_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  #    hikari:
  #      connection-timeout: 20000
  #      maximum-pool-size: ${POSTGRE_MAXIMUM_POOL_SIZE}
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        size-parameter: size
        page-parameter: page
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    com.cmcglobal: ${LOG_LEVEL}
    org.springframework: ${LOG_LEVEL}
prefix-api: ${PREFIX_API}